openapi: 3.0.1
info:
  title: short URL docs
  description: short URL docs
  version: 0.0.1
servers:
- url: http://localhost:8080
tags: []
paths:
  /urls:
    post:
      tags:
      - urls
      operationId: create-short-URL
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/urls-460719452'
            examples:
              create-short-URL:
                value: |-
                  {
                    "originalUrl" : "http://localhost:8080/too/long/url/which/is/not/easy/to/recognize/at/once"
                  }
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/urls-599923269'
              examples:
                create-short-URL:
                  value: |-
                    {
                      "code" : "CREATED_SUCCESS",
                      "data" : {
                        "originalUrl" : "http://google.com/too/long/url/which/is/not/easy/to/recognize/at/once",
                        "shortUrl" : null
                      }
                    }
  /urls/custom-url:
    post:
      tags:
      - urls
      operationId: create
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/urls-custom-url582859536'
            examples:
              create short URL:
                value: |-
                  {
                    "originUrl" : "http://localhost:8080/too/long/url/which/is/not/easy/to/recognize/at/once",
                    "target" : "custom-url"
                  }
              create-custom-URL:
                value: |-
                  {
                    "originUrl" : "http://localhost:8080/too/long/url/which/is/not/easy/to/recognize/at/once",
                    "target" : "custom-url"
                  }
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/urls-custom-url-817254599'
              examples:
                create short URL:
                  value: |-
                    {
                      "code" : "CREATED_SUCCESS",
                      "data" : "custom-url"
                    }
                create-custom-URL:
                  value: |-
                    {
                      "code" : "CREATED_SUCCESS",
                      "data" : "custom-url"
                    }
  /{value}:
    get:
      tags:
      - "{value}"
      operationId: redirect-request
      parameters:
      - name: value
        in: path
        description: Short URL
        required: true
        schema:
          type: string
      responses:
        "302":
          description: "302"
components:
  schemas:
    urls-custom-url-817254599:
      type: object
      properties:
        code:
          type: string
          description: status code
        data:
          type: string
          description: custom url
    urls-599923269:
      type: object
      properties:
        code:
          type: string
          description: status code
        data:
          type: object
          properties:
            originalUrl:
              type: string
              description: URL requested to shorten
          description: response data
    urls-460719452:
      type: object
      properties:
        originalUrl:
          type: string
          description: URL to short
    urls-custom-url582859536:
      type: object
      properties:
        originUrl:
          type: string
          description: URL to short
        target:
          type: string
          description: Custom Short URL to make from
